name: Secrets example
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          if [ "$SPOON_API_KEY" == "231" ]
          then
            echo "Got secret"
          fi          
        env: 
          SPOON_API_KEY: ${{ secrets.SPOON_API_KEY }}
          